### ISSUE TITLE
Unable to import CSV data after first import

### ISSUE THREAD

**Issue by lvschie** [litecommerce/core#34]
Hi,

I have a serious issue that wouldn't allow me to import CSV files after this has been done once. I run the latest version of LiteCommerce (1.0.24) and MySQL(5.5.24) on a Mac mini 10.7.4 server.

What I did was export the CSV file from LiteCommerce and re-import it later on. This worked once, when I tried to re-import the file after the first attempt, it just doesn't import anything, and does not give an error.

Anny suggestions?

**Comment by lvschie** [comment]
This issue is still not solved after 7 months, please assist!

**Comment by fundaev** [comment]
Sorry for the deay. The problem was already fixed in LiteCommerce 3 v1.1.3. Please upgrade your store to avoid this problem.

**Comment by lvschie** [comment]
Thanks for the reply, I'm currently running the latest version of LiteCommerce 3 (1.1.3) and the problem still exists. When importing CSV files after dropping the LiteCommerce/Drupal databases and recreating them, it works. But after I've once imported a product database (CSV) it doesn't, until I drop the databases again and do the procedure all over again. Anny suggestions?

**Comment by fundaev** [comment]
Do you try to import the CSV file with products via "Catalog"->"Import" page? Or try to restore the database via "Maintenance"->"Restore" page?

**Comment by lvschie** [comment]
Through the "Import" page. Can you import CSV files through the "Restore" page?

**Comment by lvschie** [comment]
Could you please fix this issue, otherwise I must migrate to another webshop because it's a huge issue that takes up a lot of our time, rendering this software useless.

**Comment by maxmukhin** [comment]
Could you please attach the CSV file which produces the issue?

We could not reproduce it with the current LC version.

Thank you in advance.

**Comment by lvschie** [comment]
Sent it to the email address in your account information. It contains sensitive information, hence the email. ;)
